### ISSUE TITLE
iOs support ?

### ISSUE THREAD

**Issue by dcz-switcher** [CartoDB/Leaflet.CanvasLayer#1]
Thanks to share your great work.

Do you plan to support iOS ?

I tested on iPad 1, and the animation was not displayed

**Comment by javisantana** [comment]
@davtwix it works on some versions of iOS but I have no idea from what version it does. What is your iOS version?

**Comment by dcz-switcher** [comment]
thanks to reply

I use an iPad1 with iOS 5.1.1 ... I understand if you choose to not support this old version, it's like on android, before 4.3, android web view sucks

**Comment by javisantana** [comment]
the thing is that those devices AFAIK support canvas. I will take a look

**Comment by javisantana** [comment]
@davtwix I think it should work on ipad1 now, could you check?

**Comment by javisantana** [comment]
I checked it and it works
